export enum MimeTypes {
    APPLICATION_JSON = 'application/json;charset:utf-8,',
    APPLICATION_PDF = 'application/pdf;charset:utf-8,',
    APPLICATION_MSWORD = 'application/msword;',
    APPLICATION_XML = 'application/xml;charset:utf-8,',
    APPLICATION_ZIP = 'application/zip;',
    APPLICATION_GZIP = 'application/gzip;',
    APPLICATION_OCTET_STREAM = 'application/octet-stream;',
    AUDIO_MPEG = 'audio/mpeg;',
    AUDIO_WAV = 'audio/wav;',
    AUDIO_OGG = 'audio/ogg;',
    IMAGE_JPEG = 'image/jpeg;',
    IMAGE_PNG = 'image/png;',
    IMAGE_GIF = 'image/gif;',
    TEXT_PLAIN = 'text/plain;charset:utf-8,',
    TEXT_HTML = 'text/html;charset:utf-8,',
    TEXT_CSS = 'text/css;charset:utf-8,',
    TEXT_JAVASCRIPT = 'text/javascript;charset:utf-8,',
    VIDEO_MP4 = 'video/mp4;',
    VIDEO_MOV = 'video/quicktime;',
    VIDEO_AV1 = 'video/av1;',
}